import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './src/features/layout/Header'
import DevblogEditor from './src/features/layout/DevblogEditor'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

    return (
        <html lang="en" className='h-full'>

            <body className={clsx(inter.className, 'bg-background h-full') }>

                <Header/>
                <div className='bg-background h-20 bg-gray-100'></div>

                <div className="container mx-auto p-4">

                <DevblogEditor/>
                {children}

                </div>
                
            </body>

        </html>
    )
}
